Repository seizmeia/seizmeia, pull requests merged in 2022-03, with the labels that each got.

#13 Organized package code and added pre-commit
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  Dockerfile
  LICENSE.txt
  Makefile
  README.md
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  seizmeia.yml
  seizmeia/__main__.py
  seizmeia/auth.py
  seizmeia/config.py
  seizmeia/health.py
  seizmeia/server/__init__.py
  seizmeia/server/auth/__init__.py
  seizmeia/user.py
  seizmeia/uvicorn.py
  seizmeia/version.py
  setup.cfg
  tests/__init__.py
  tests/auth_test.py
  tests/health.py
  tests/health_test.py
  tox.ini
Labels: enhancement, tech debt

#14 Default configuration and configuration from yaml now are class methods
  seizmeia/__main__.py
  seizmeia/config.py
Labels: enhancement

#15 general maintenance updates to config files and tools
  .github/workflows/publish.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  pyproject.toml
  setup.cfg
Labels: tech debt
